config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controllers: { :registrations => "registrations", :sessions => "sessions" }
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root "pages#home"
    resources :users, only: [:show, :create, :new]
    resources :accounts, only: [:show, :create, :new]
    resources :transactions, only: [:create, :new]
end

app/models/user.rb
class User < ApplicationRecord
    has_paper_trail
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable, :validatable, :rememberable
    
    validates :name, presence: true
    validates :risk_tolerance, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }

    has_many :accounts, :dependent => :destroy

    def total_balance
        total = 0
        return total if self.accounts.count < 1
        self.accounts.each do |account|
            total += account.available_balance
            total += account.asset_balance
        end
        total
    end

    def balance_history
        result = {}
        self.accounts.each do |account|
            account.versions.where(:event => "update").each do |version|

                # Sets balance_at_time to zero
                # This will accumulate as we work through all accounts and tally the balance_at_time
                balance_at_time = 0

                # To distinguish between object itself and version object
                object = version.reify

                self.accounts.each do |comp_account|
                    version_at_time = comp_account.paper_trail.version_at(version.created_at)
                    next if version_at_time == nil
                    balance_at_time += version_at_time.asset_balance
                    balance_at_time += version_at_time.available_balance
                end

                result[version.created_at] = balance_at_time

            end
        end
        result
    end

end

app/controllers/users/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
        @accounts = @user.accounts
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, only: [:show]
    def show
        @user = User.find(params[:id])
        @accounts = @user.accounts
    end

    def new
        @user = User.new
    end

end

app/views/users/show.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

<div class="columns has-text-centered mt-5">
    <div class="column"></div>
    <div class="column">
        <h4 class="subtitle is-6 mt-6">Hello <%= current_user.name %>, you have</h4>
        <h2 class="title is-1">$<%= current_user.total_balance %></h2>
    </div>
    <div class="column"></div>
</div>

<%= area_chart @user.balance_history, colors:["#ffdd57"], curve: false, discrete: true, empty: "No data", library: {
    hAxis: { textPosition: "none" },
    vAxis: { textPosition: "none", gridlines: { color: "transparent" } },
    backgroundColor: { fill: "transparent" },
    chartArea: { width: "100%" }
} %>

<div class="columns has-text-centered mt-5">
    <div class="column"></div>
    <div class="column">
        <% if current_user.accounts.count > 0 %>
            <h2 class="title is-4">Accounts</h2>
            <% current_user.accounts.each do |account| %>
                <div class="box">
                    <div class="columns">
                        <div class="column">
                            <h3 class="title is-6 mb-4">Name</h3>
                            <%= account.name %>
                        </div>
                        <div class="column">
                            <h3 class="title is-6 mb-4">Invested in</h3>
                            <%= account.holding.asset.ticker %>
                        </div>
                        <div class="column">
                            <h3 class="title is-6 mb-4">Value</h3>
                            $<%= account.asset_balance %>
                        </div>
                    </div>
                    <%= button_to("See account", account, :method => :get, class: "button is-warning is-rounded")  %>
                </div>
            <% end %>

            <%= button_to("Open a new account", new_account_path, :method => :get, class: "button is-black is-rounded")  %>
        <% else %>
            <div class="box">
                <h2 class="title is-3">You have no accounts yet</h2>
                <%= button_to("Open an account", new_account_path, :method => :get, class: "button is-warning is-rounded")  %>
            </div>
        <% end %>

    </div>
    <div class="column"></div>
</div>