config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controllers: { :registrations => "registrations", :sessions => "sessions" }
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root "pages#home"
    resources :users, only: [:show, :create, :new]
    resources :accounts, only: [:show, :create, :new]
    resources :transactions, only: [:create, :new]
end

app/views/pages/home.html.erb
<nav class="navbar p-5" role="navigation">
    <div class="navbar-brand">
        <div class="navbar-item"><img src="https://www.wealthsimple.com/static/ws-wordmark-7a6a6ea384e8586aaeb2597547f86158.svg"></div>
    </div>

    <div class="navbar-menu">
        <div class="navbar-end">
            <%= button_to("Log in", user_session_path, :method => :get, class: "button", style: "border: none")  %>
            <%= button_to("Get started", new_registration_path(@user), :method => :get, class: "button is-warning is-rounded")  %>
        </div>
    </div>
</nav>

<div class="columns has-text-centered is-vcentered">
    <div class="column p-6">
        <h2 class="title is-1 mb-6">Get rich slow</h2>
        <h3 class="subtitle is-4">Powerful financial tools to help you grow and manage your money</h2>
        <%= button_to("Get started", new_registration_path(@user), :method => :get, class: "button is-warning is-rounded is-large")  %>
    </div>
    <div class="column">
        <video autoplay loop>
            <source src="https://www.wealthsimple.com/static/2-human-powered-medium-flipped-ff2af165abcda24b72d11d55c8431543.mp4" type="video/mp4">
        </video>
    </div>
</div>