config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controllers: { :registrations => "registrations", :sessions => "sessions" }
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root "pages#home"
    resources :users, only: [:show, :create, :new]
    resources :accounts, only: [:show, :create, :new]
    resources :transactions, only: [:create, :new]
end

app/models/account.rb
class Account < ApplicationRecord
    has_paper_trail
    validates :name, presence: true

    belongs_to :user
    has_one :holding, :dependent => :destroy
    has_many :transactions, :dependent => :destroy

    after_create :add_holding

    def rebalance
        return if self.available_balance == 0
        self.transactions.create(:amount => self.available_balance, :description => "Investment")
    end

    def update_available_balance(amount)
        new_balance = self.available_balance + amount
        return false, "Transaction exceeds available balance" if new_balance < 0
        self.update(:available_balance => new_balance)
    end

    def update_asset_balance(amount)
        new_balance = self.asset_balance + amount
        return false, "Transaction exceeds available balance" if new_balance < 0
        self.update(:asset_balance => new_balance)
    end

    def add_holding
        return if Asset.count == 0
        asset = Asset.where(riskiness: self.user.risk_tolerance).first
        return if asset == nil
        self.create_holding(:asset_id => asset.id, :units => 0)
    end

    def balance_history
        result = {}
        self.versions.where(:event => "update").each do |version|
            object = version.reify
            result[version.created_at] = object.available_balance + object.asset_balance
        end
        result
    end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    before_action :authenticate_user!

    def new
        @account = Account.new
    end

    def create
        @account = Account.new(account_params)
        respond_to do |format|
            if @account.save
                format.html { redirect_to @account }
            else
                format.html { render :new }
            end
        end
    end

    def show
        @account = Account.find(params[:id])
        @transactions = @account.transactions.order("created_at DESC")
        @holding = @account.holding
    end

    private

    def account_params
        params.require(:account).permit(:name, :user_id, :available_balance)
    end

end

app/views/accounts/new.html.erb
<div class="columns has-text-centered mt-5">
    <div class="column"></div>
    <div class="column">
        <div class="box">
            <h2 class="title is-2">Create an account</h2>
            <% if @account.errors.any? %>
                <div class="notification is-danger">
                    <% @account.errors.each do |error| %>
                        <%= error.full_message %></br>
                    <% end %>
                </div>
            <% end %>
            <%= form_for @account do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.text_field :name, placeholder: "Give your account a nickname", class: "input is-fullwidth mb-4" %>
                <%= f.submit class: "button is-fullwidth is-warning is-rounded" %>
            <% end %>
        </div>
    </div>
    <div class="column"></div>
</div>

app/views/accounts/show.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

<div class="columns has-background-white has-text-centered">
    <div class="column"></div>
    <div class="column"></div>
    <div class="column">
        <h3 class="title is-5">Account name</h3>
        <h4 class="subtitle is-4"><%= @account.name %></h4>
    </div>
    <div class="column">
        <h3 class="title is-5">Account value</h3>
        <h4 class="subtitle is-4">$<%= @account.asset_balance + @account.available_balance %></h4>
    </div>
    <div class="column">
        <h3 class="title is-5">Invested in</h3>
        <h4 class="subtitle is-4"><%= @account.holding.asset.ticker %></h4>
    </div>
    <div class="column">
        <%= button_to("Fund this account", new_transaction_path, :method => :get, class: "button is-warning is-rounded")  %>
    </div>
    <div class="column"></div>
</div>

<%= area_chart @account.balance_history, colors:["#ffdd57"], empty: "No data", curve: false, discrete: true, library: {
    hAxis: { textPosition: "none" },
    vAxis: { textPosition: "none", gridlines: { color: "transparent" } },
    backgroundColor: { fill: "transparent" },
    chartArea: { width: "100%" }
} %>

<div class="columns has-text-centered mt-5">
    <div class="column"></div>
    <div class="column">
        <% if @account.transactions.count > 0 %>
            <div class="box">
                <h2 class="title is-2 mb-6">Transactions</h2>
                <% @transactions.each do |transaction| %>
                    <div class="columns">
                        <div class="column">
                            <h3 class="title is-6 mb-4">Date</h3>
                            <%= transaction.created_at.strftime('%d %b %H:%M') %>
                        </div>
                        <div class="column">
                            <h3 class="title is-6 mb-4">Type</h3>
                            <%= transaction.description %>
                        </div>
                        <div class="column">
                            <h3 class="title is-6 mb-4">Amount</h3>
                            $<%= transaction.amount %>
                        </div>
                    </div>
                <% end %>
            </div>
        <% else %>
            <div class="box">
                <h2 class="title is-3">No transactions to show yet</h2>
                <%= button_to("Fund this account", new_transaction_path, :method => :get, class: "button is-warning is-rounded")  %>
            </div>
        <% end %>
    </div>
    <div class="column">
        <div class="box">
            <h2 class="title is-2 mb-6">Deposit insights</h2>
            <%= column_chart @account.transactions.where(:description => "Deposit").group_by_day(:created_at).sum(:amount), colors:["#387474"], empty: "No data" %>
        </div>

        <div class="box">
            <h2 class="title is-2 mb-6">Portfolio</h2>

            <div class="columns">
                <div class="column">
                    <h3 class="title is-6 mb-4">Asset</h3>
                    <%= @holding.asset.ticker %>
                </div>
                <div class="column">
                    <h3 class="title is-6 mb-4">Units</h3>
                    <%= @holding.units %>
                </div>
                <div class="column">
                    <h3 class="title is-6 mb-4">Risk</h3>
                    <%= @holding.asset.riskiness %>
                </div>
            </div>

            <div class="columns">
                <div class="column">
                    Cash
                </div>
                <div class="column">
                    <%= @account.available_balance %>
                </div>
                <div class="column">
                    <%= 0 %>
                </div>
            </div>

        </div>
    </div>
    <div class="column"></div>
</div>